---
curriculumDir: /home/mierdin/Code/nre-learning/antidote-test-curriculum
instanceId: antidote-dev
enabledServices:
- api
- stats
- scheduler


backend: kubernetes
backendConfigs:
  kubernetes:

    # for dev
    inCluster: false
    outOfClusterConfigPath: "/home/mierdin/.kube/selfmedicateconfig"

