
cat <<EOT >> ./cmd/syringed/buildinfo.go
package main

/*
This file is automatically generated by Syringe build scripts.
Please do not edit.
*/

var (
	buildInfo = map[string]string{
		"buildSha": "$(git rev-parse HEAD)",
	}
)

EOT
